### ISSUE TITLE
Vanilla Example that is not type-script & usable via <script> tag

### ISSUE THREAD

**Issue by Mashiane** [junobuild/examples#10]
Good day..

Thanks for your examples. I am wondering, is it possible to get a CDN version of your example for VanillaJS that is not written in types-script?

I am looking for something that can be used via the script tag perhaps from a dist folder that I can explore.

Thank you so much

**Comment by peterpeterparker** [comment]
Hi @Mashiane ,

Sure sounds doable, I can put together a plain HTML/JS example with no bundler. Any preferred CDN?

**Comment by Mashiane** [comment]
That will be awesome. I cant wait and excited. Any CDN is fine I guess.

**Comment by peterpeterparker** [comment]
Great! I might not have the time today but, will try to cook something soon.

**Comment by peterpeterparker** [comment]
Just added a sample that uses Juno through a CDN and interact with Authentication, Datastore and Storage.
Does it answer your question or do you need more details?

https://github.com/buildwithjuno/examples/blob/main/vanilla/cdn-javascript/index.html

**Comment by peterpeterparker** [comment]
Given that I did not answer anything back, I'm assuming it worked out, therefore closing this.
If not, please let me know, we can reopen the request.
